### PR TITLE
A few ideas on FrameworkInterop

### PR DESCRIPTION
**Pull request by moufmouf**
Hi Matthieu,

I just took a closer look at framework-interop today and decided to spend some time looking at how it works.

I've been making a few changes in a fork. I'd like to know what you think about those. I'm submitting this pull-request so that you can easily view the changes I made. Feel free to reject it if you don't like it.
## Module vs ModuleInterface

I wrote a `ModuleInterface` interface instead of the abstract `Module` class.

Your `Module` class is forcing the signature of the constructor (it must be passed a rootContainer).
I pass the $rootContainer argument as a parameter of `getContainer`. Therefore, the rootContainer is still
available to the module, but there is no obligation to respect a constructor signature anymore.

Therefore, I modified the `Application` class so that the array of modules passed to the constructor
can be an array of strings or modules instances rather than an array of strings only.
## ModuleInterface: removing `getHttpApplication` and adding `init`

The `getHttpApplication` returns a `HttpKernelInterface` object. It is a half standard because there is StackPHP around.
We know that it will become obsolete when PSR-7 is out.
And anyway, the notion of `HttpKernelInterface` is useless for CLI applications or for libraries that are not web-related.

Here is an idea:

Let's replace `getHttpApplication` and `getCommands` with a more generic `init` method.

By convention, we declare that if the application is a web application, it MUST inject in the rootContainer an instance named "stackBuilder" (an object of the `Stack\Builder` class). StackBuilder is a class allowing to chain middlewares more easily in StackPHP.

Why is it great? Each module does not have to be separated into a sub-url.
We can "push" or "unshift" middlewares on the stack, so a module could decide to provide error handling functionnality (like "Whoops") by pushing itself at the front of the stack to catch all URLs. So basically, a module can do more than just claiming a part of the URL namespace.

Note: I had to cheat a little bit here. Stack\Builder needs Middlewares, but neither a Symfony app or a Silex app or a ZF1 app are middlewares. Therefore, I wrote "mouf/silex-middleware", a StackPHP middleware that transforms a Silex app into a middleware. For the SF2 and ZF1 app, I'm using the `UrlMap` middleware.

Also, it would be trivial to implement a `HttpKernelModule` class that mimicks the `Module` class by implementing
the `init` method and exposing an abstract `getHttpApplication` method (just like today).

Also, I completely removed the `$app->setWebRoutes` part. The use of UrlMap middleware makes those webRoutes useless.
Therefore, I also removed the `HttpRouter` class that was not needed anymore.
## Ideas to come

I still have plenty of other ideas! First, I would like to try to cut your demo application into many small packages.

I would isolate the `ModuleInterface` interface into its own Composer package.

I think your `Application` class might be one of many valid implementations of an application.
I would be willing to write my own implementation, that provides a composer installer that tries to auto-detect
modules extending `ModuleInterface` and automatically add them to the src/app.php file.

What do you think about these ideas? Are you planning to work on framework-interop in the coming month or was it just a test project?
I am planning to work on a new project (a fork of Mouf that provides a flexible web-based development UI, without the DI part). The idea is to replace the typical use of a console with a web-app dedicated to developer instead (one that would let you purge the cache of your project, generate doctrine entities, generate controllers, etc...). I need a flexible module system for this and I feel this could very well be the basis of it :)

### CODE REVIEW

**Comment by mnapoli** [comment]
### Module vs ModuleInterface

+1, interface is much better

### ModuleInterface: removing `getHttpApplication` and adding `init`

First off, +1 with going with Middlewares instead of HttpKernelInterface, this is the way to go these days!

> Why is it great? Each module does not have to be separated into a sub-url.

Yeah this is pretty awesome, I love your idea.

> Let's replace getHttpApplication and getCommands with a more generic init method.

I'm not 100% sure about either way. I don't specifically like `getHttpApplication` because it means writing in stone that a module is a HTTP + a CLI application. Then what happens when there's a good abstraction and implementations for websockets? or any other kind of applications…

So at first thought, +1 with that change. But then letting a module declare X or Y and letting the app/end-user register it is more "inversion of control" than letting the module manipulate a global configuration to register itself. And `init()` is kind of generic and calling to all kind of abuses.

Also your solution relies on a `stackBuilder` container entry, which is way too much for me ;) I really don't like that, maybe we can find another solution with `init()`.

Here is an alternative idea to the current interface:

``` php
interface Module {
    public function getContainer(...);
}
interface HttpModule extends Module {
    public function getHttpMiddleware(...);
}
interface CliModule extends Module {
    public function getCliMiddleware(...);
}
...
```

A module can implement many interfaces. That way, we can later add e.g. `WebSocketModule` or whatever.

> Are you planning to work on framework-interop in the coming month or was it just a test project?

It was meant as a test project, I don't think it's fair for you to work in this repo if you do all the work ;). I'd happily continue discussing all this and maybe collaborate in another repo? Feel free to take code from here or not.

> The idea is to replace the typical use of a console with a web-app dedicated to developer instead

Very interesting idea!

**Comment by moufmouf** [comment]
Hi Matthieu,

Thanks or the positive feedback!

> But then letting a module declare X or Y and letting the app/end-user register it is more "inversion of control" than letting the module manipulate a global configuration to register itself.

Yeah, I understand your feeling. Also, relying on StackBuilder is a bit hard, I agree. I'll try to think about another solution. One important part I feel is that if a module adds a middleware, it must be able to add it at the front or at the back of the middleware list (or possibly provide a rank for the middleware).

> It was meant as a test project, I don't think it's fair for you to work in this repo if you do all the work ;). I'd happily continue discussing all this and maybe collaborate in another repo? Feel free to take code from here or not.

Ok, I'll create a "framework-interop" organization in Github and put the 2 of us in it. I'll split the project into many small packages to get a feeling of what it would look like.

**Comment by mnapoli** [comment]
Awesome!

Regarding order and priorities, it could be related to the order in which modules are registered? E.g. register the "Whoops" module first (and it makes sense for the end user).

**Comment by moufmouf** [comment]
> Regarding order and priorities, it could be related to the order in which modules are registered? E.g. register the "Whoops" module first (and it makes sense for the end user).

I understand that we could use the modules order to register which router is registered first. However, this module order is also used for the containers put in the `rootContainer`.

Therefore, the routers order and the containers order would have to be the same. I'm not sure that it will always be true... on the other end, I must say I cannot find a use case where the container order and the routers order would have to differ...

**Comment by moufmouf** [comment]
Hi Matthieu,

I just added a `HttpModuleInterface` that can return a Stack middleware.
I created the project https://github.com/framework-interop/framework-interop-demo and put you in the framework-interop organisation.

Starting from here, I'll split the project into many smaller packages. So I'll close this pull-request and we can start the discussion over here: https://github.com/framework-interop/framework-interop-demo

**Comment by mnapoli** [comment]
:+1:

**Pull request closed without merging**
